### ISSUE TITLE
Add task_schedule3 and watch_cron_logs3

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3-static#4]
Need for cron job processing.

**Comment by jeanconn** [comment]
Though for conda packages it isn't clear to me if we want to manage the source to these or any changes to these directly from their conda recipes or?

**Comment by jeanconn** [comment]
Mostly meaning, should we

1) get the already-made task_schedule3.pl and watch_cron_logs3.pl scripts and put them in a recipe to get directly copied into the conda env bin

2) have the conda recipe get the source for the two projects and use the Makefile to install (probably just setting SKA_ARCH_OS to PREFIX in the conda recipe build.sh).

**Comment by taldcroft** [comment]
I had assumed something like option 2.  

In option 1, I don't know where the "already made" files come from and how that process gets automated so we can start from a clean repo and get to the built conda package.  But if you have an idea I don't feel that strongly.

Option 3 could be to branch current master for task_schedule and watch_cron logs to `ska2` branches, and then make the changes so that the going-forward master is only for ska3.  I.e. actually just change the file names in the repo and change `make install` to install the *3 versions.  The rename to *3 is being super conservative, but would definitely prevent accidentally overwriting the ska2 versions.  Which is being super conservative because it should work in ska2, I just don't want to experimentally find out in Ska2 flight.

I kind of like option 3 because the whole sed stuff is garbage, but whatever works.. eventually there will really only be Ska3 and we can clean up as needed.

**Comment by jeanconn** [comment]
For the "already made" files, I just meant that I'd take the current task_schedule.pl and watch_cron_logs.pl, edit the tops of those files (or run your sed) and put them in the conda recipe.  Given the frequency of updates to task_schedule.pl and watch_cron_logs.pl I don't see that the make process would need to be automated.

I'm also fine with your option 3 (I had also considered updating the repos or making new ones or whatever).  For option 3 we don't actually have to make the py3 changes in master (newer tags on a py3 branch would still work for the conda updates, I think).  But whatever is more self-documenting works for me.

**Comment by jeanconn** [comment]
Though if we don't want task_schedule3.pl and watch_cron_logs3.pl to just be plain files in a tarball or in the conda recipe, and instead want to be tracking a git repo, both tools should then be in the 
skare3 repo not the basically-static skare3-perl repo.

**Comment by jeanconn** [comment]
Then again, it could also be simpler to combine the skare3-perl and skare3 repos and just add all the skare3-perl recipes to the "no_source_packages" list in the skare3 builder, which is basically a "don't do anything fancy with git for these packages" list.

**Comment by jeanconn** [comment]
These are now installed from skare3
